### ISSUE TITLE
item list is empty

### ISSUE THREAD

**Issue by muralikodali** [fdw/rofi-rbw#11]
rofi-rbw is showing up no items and it is asking for bitwarden password every time.

**Comment by fdw** [comment]
If you call `rbw list` on the command line, what happens?

**Comment by muralikodali** [comment]
`rbw list` gives following error :  

```
rbw list: failed to log in to bitwarden instance: failed to parse JSON: .: expected value at line 1 column 1: expected value at line 1 column 1
```

**Comment by fdw** [comment]
Then the problem is with `rbw`. I think I had a similar error once, and removing `.cache/rbw` might have helped, but I'm not sure.
Good luck!

Also, if you can tell me what status code `rbw list` returns, I can try to add an error message to `rofi-rbw`.

**Comment by muralikodali** [comment]
`rbw list` returns the same error message. no status code is found.

I have tried on your suggestion, to remove .cache/rbw. but no use.
There is nothing stored in .cache/rbw.

**Comment by fdw** [comment]
I think your error look a lot like https://github.com/doy/rbw/issues/57 . There's nothing I can do in `rofi-rbw`.

**Comment by muralikodali** [comment]
so, it is the api access problem.

Thanks

**Comment by jonathannerat** [comment]
@muralikodali It's working again in case you're wondering. Totally random

**Comment by muralikodali** [comment]
yes, it is working again and asking for 2FA code along with password
