### ISSUE TITLE
xdotool typing seems broken

### ISSUE THREAD

**Issue by cstrahan** [fdw/rofi-rbw#15]
Having trouble with auto typing user/pass -- the current approach isn't working in Chrome, gedit, Gnome Terminal, etc (the applications appear to ignore the sent keys entirely).

Per the "SENDEVENT NOTES" section of the `xdotool` man page (http://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html#sendevent%20notes):

       If you are trying to send key input to a specific window, and it does not appear to be
       working, then it's likely your application is ignoring the events xdotool is generating.
       This is fairly common.

       Sending keystrokes to a specific window uses a different API than simply typing to the
       active window. If you specify 'xdotool type --window 12345 hello' xdotool will generate
       key events and send them directly to window 12345.  However, X11 servers will set a
       special flag on all events generated in this way (see XEvent.xany.send_event in X11's
       manual). Many programs observe this flag and reject these events.

       It is important to note that for key and mouse events, we only use XSendEvent when a
       specific window is targeted. Otherwise, we use XTEST.

       Some programs can be configured to accept events even if they are generated by xdotool.
       Seek the documentation of your application for help.

       Specific application notes (from the author's testing): * Firefox 3 seems to ignore all
       input when it does not have focus.  * xterm can be configured while running with
       ctrl+leftclick, 'Allow SendEvents' * gnome-terminal appears to accept generated input by
       default.

Tried changing the `type_characters` function to this, and looks like things are now working:

```python
    def type_characters(self, characters: str, active_window: str) -> None:
        run([
            'xdotool',
            'windowactivate',
            '--sync',
            active_window,
            'type',
            '--clearmodifiers',
            characters
        ])
```

The idea being to explicitly activate the previous window and then send the chars.

```
cstrahan@pop-os:~/src/xsel$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Comment by fdw** [comment]
I was quite sure I had tried something similar before, but I can't find any trace of that. So, let's try this again. 🙂

It's now on `main`, and I haven't noticed any regression so far. I don't use Chrome or Gnome, so I didn't notice any improvement, either 😉 But please test it, and if it works, we can release it.
