### ISSUE TITLE
[Feature Request] Custom field support

### ISSUE THREAD

**Issue by RilicTheFox** [fdw/rofi-rbw#17]
Is there any chance of custom field support at all? When hitting enter on a selected item, it could bring up a menu with all of its fields. Hitting enter again on a selected field could autotype its value.

**Comment by fdw** [comment]
That's a very interesting idea, thanks 🙂

I'm wondering if this should be the default action, though. I expect most people usually want to auto-type the password. What do you think?
In any case, offering a menu as an option sounds good to me. Do you want to try your hand at this?

**Comment by RilicTheFox** [comment]
It's been a long while since I last used Python, nevermind make something functional with it. But I could give it a try!

I switched back to Bitwarden from KeePass today after an incident where I nearly lost my database, which would've locked my out of every account I have ever owned. :grimacing: I used [keepmenu](https://github.com/firecat53/keepmenu) with it, which is a tool similar to this where the default action is to autotype both the username and password, as well as having an option to open a menu that allows you to autotype particular fields. I think a similar menu should be opened by pressing a certain keycombo.

Side thought, this means this tool could work with credit card/identity autofill too! Though that is up to you, since the web extension already covers most cases where you'd want those features. But it *could* eliminate the need for it to be installed on the browser.

**Comment by fdw** [comment]
> It's been a long while since I last used Python, nevermind make something functional with it. But I could give it a try!

I didn't want to pressure you, just offering the chance. I can do it too, when I have time 🙂

> I think a similar menu should be opened by pressing a certain keycombo.

That does sound good to me :) `rofi-rbw` also has an `--action` parameter to define the default action, where we could offer `menu` as well, I think.

> Side thought, this means this tool could work with credit card/identity autofill too! 

Why not? We should at least try 😉

Also, welcome back to Bitwarden! Hope you don't lose your passwords!

**Comment by fdw** [comment]
I think I'll have a go at this, if you don't mind :)

**Comment by fdw** [comment]
Please try it out 🙂

**Comment by RilicTheFox** [comment]
The current commit isn't displaying the menu at the moment :( It's just autotyping the password for me.

Also, I'm having trouble when the autotyped content includes special characters. It messes up the keyboard layout to the point where only a few keys work and they aren't the right letters. I feel I should make a separate issue for this, though, since it also happened in the release version for me. Should I?

**Comment by fdw** [comment]
>The current commit isn't displaying the menu at the moment :( It's just autotyping the password for me.

Have you invoked it with `--action=menu`?

> I feel I should make a separate issue for this, though, since it also happened in the release version for me. Should I?

Yes, please! That sounds very weird and not good. If you can, please also mention if you use unusual keyboard settings and which characters are problematic (only if that is okay, obviously).

Thank you!

**Comment by RilicTheFox** [comment]
> Have you invoked it with `--action=menu`?

Ah, that works! That's really handy! Just one thing, it shows passwords and "hidden" custom fields in plaintext, which isn't great in my opinion.

Then again, [some people like it unmasked](https://www.nngroup.com/articles/stop-password-masking/), so maybe make that another option for accessibility? That's up to you-

> Yes, please! That sounds very weird and not good. If you can, please also mention if you use unusual keyboard settings and which characters are problematic (only if that is okay, obviously).

I'll get to it! Cheers

**Comment by fdw** [comment]
Yes, showing confidential stuff in plain text is not the best idea, I agree. So, we can hide the password, but what about the others? Hide them all?

I'm hestitant to add another option for this, as it makes both the code and the usage more complicated. I'd much rather find a good compromise that works for everyone.

**Comment by RilicTheFox** [comment]
> Yes, showing confidential stuff in plain text is not the best idea, I agree. So, we can hide the password, but what about the others? Hide them all?

Is there a way to discern between "hidden" and "non-hidden" custom fields using rbw? That might help, and would also be a compromise to the latter question imo. The actual name of the hidden field could be visible to tell you what its contents are for.

**Comment by fdw** [comment]
No, `rbw` doesn't seem to give out information about. I've opened an issue for that.

Until then, how about we hide everything except URI and username? I tend to hide rather all fields, as you usually wouldn't use `rofi-rbw` to just read something, would you?

**Comment by RilicTheFox** [comment]
> Until then, how about we hide everything except URI and username? I tend to hide rather all fields, as you usually wouldn't use rofi-rbw to just read something, would you?

That seems fair, honestly! I, for one, would be okay with that until `rbw` comes up with a way to check hidden status on the fields.  It would just feel a bit more integrated, in my opinion.

**Comment by fdw** [comment]
Here, I've tried something 🙂

**Comment by RilicTheFox** [comment]
Nice, that works! Pins and stuff might still be a problem since they're quite short already, but that's a neat compromise.
On entries for credit cards, the card number is listed as "password". I think adding per-type strings for the text in the list might help with this, but that sounds like it would complicate what I assume is meant to be a simple script. It functionally works, anyway!

**Comment by fdw** [comment]
> I think adding per-type strings for the text in the list might help with this

Yup, that would be nice, but I don't think I can get the type from the entry at the moment. We could try some "if it has an `Expiration`, it must be a credit card", but I'm not sure I want to go there.

**Comment by fdw** [comment]
Waiting for https://github.com/doy/rbw/issues/67

**Comment by dataO1** [comment]
As far as i can see, the only option with the menu is to autotype the content of custom fields. I usually need to copy the content, would it be possible to add that option somehow to the action parameter? 
Something like `action=menu-clipboard` or similar?

**Comment by fdw** [comment]
That sounds like an interesting idea, thanks 🙂

I'll need to think how to implement this, as I don't want to have too many `Actions`.

**Comment by fdw** [comment]
As you can see, I've added something. Can you please try it and see if it works for you?

**Comment by dataO1** [comment]
@fdw I tested it on main and it works just as expected, looks good to me :) thanks for taking the time!

**Comment by fdw** [comment]
Awesome 🙂

I'll close this ticket then, as I don't think https://github.com/doy/rbw/issues/67 will be fixed soon.

**Comment by fdw** [comment]
Finally, `rbw` returns the type of a field, and I've now implemented it in `rofi-rbw`, too 🙂
