### ISSUE TITLE
[Feature request] Use rofi to request vault password

### ISSUE THREAD

**Issue by aacebedo** [fdw/rofi-rbw#18]
Hi !
I switch from bitwarden-pyro to rofi-rbw as pyro seems not maintained anymore.
Pyro can use rofi to request the vault password, this choice allows for a more integrated design as the window to display the credentials and the window to asks for the password are the same.
I was wondering if rofi-rbw could offer the same possibility ?

I did the modification for pyro here https://github.com/mihalea/bitwarden-pyro/pull/7 (it was never merged unfortunately).

I can make the modifications to rofi-rbw if you are ok

**Comment by fdw** [comment]
Hey, thanks for the idea :)

I just had a very quick look at `rbw`, and it seems that you can't pass it the password for `unlock`. However, maybe you can find some documentation for that, or open a feature request.

**Comment by aacebedo** [comment]
You are right. I'll try to create a FR in rbw

**Comment by fdw** [comment]
Blocked by https://github.com/doy/rbw/issues/65 :/

**Comment by fdw** [comment]
Since rbw hasn't seen a lot of development lately, I'll close this issue. When the feature lands there, we can open it again.
