### ISSUE TITLE
[Bug] Keyboard layout messed up when autotyping special characters

### ISSUE THREAD

**Issue by RilicTheFox** [fdw/rofi-rbw#19]
When I autotype passwords that includes characters that aren't normal letters or numbers, the keyboard layout gets scuffed beyond repair until manual reboot. I don't know of any corralation between the characters typed and the change being changed, but most of the alphabetical keys are rendered non-functional and some are mixed and matched, including the meta key, ESC, etc.

I'm using a bspwm+sxhkd setup on Arch Linux, and some of the passwords were imported from KeePass which uses way more character types than Bitwarden's password generator. That *may* have something to do with it.

**Comment by fdw** [comment]
Thank for opening this issue 🙂

I also have passwords with weird characters, but I haven't noticed anything so far.
However, could it be that you've been hit by https://github.com/jordansissel/xdotool/issues/43 ? Specifically, that you start `rofi-rbw` with meta/alt/ctrl, let go of that key and `xdotool` then restores it again? I've had that happen to me previously, and pressing `alt` some times made it work again.

**Comment by RilicTheFox** [comment]
> could it be that you've been hit by jordansissel/xdotool#43 ?
Doesn't seem like it, sadly. The whole keyboard layout gets messed up, not just the modifier keys.

I'm beginning to suspect it might actually be something wrong with how my system is configured, but I wouldn't be sure where to start honestly. I'll see what the Arch Wiki says about keyboard layouts and follow the steps to ensure that everything is correct on my end.

**Comment by fdw** [comment]
Do you have multiple keyboard layouts defined? If so, how do you switch between them?

**Comment by RilicTheFox** [comment]
I only have one keyboard layout defined, that being gb.

[Printing the settings](https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Viewing_keyboard_settings) outputs this:
```
> setxkbmap -print -verbose 10                                                                  ~
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     gb
variant:    ,
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+gb+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+gb+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```
It's set by systemd:
```
> cat /etc/X11/xorg.conf.d/00-keyboard.conf                                                     ~
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "gb"
        Option "XkbModel" "pc105"
        Option "XkbVariant" ","
EndSection
```

Interestingly, while using [keepmenu ](https://github.com/firecat53/keepmenu)for KeePass, it had a weird problem where it would use a different keyboard layout (I'm assuming US) and get a *few* characters wrong while autotyping, but it was always fine after that. This seems like a similar issue, and I think this might be related: https://github.com/firecat53/keepmenu/issues/59

**Comment by fdw** [comment]
So far, I don't see the problem in `rofi-rbw` :/

Maybe, if you have the time, you can try to find out which characters (or sequence of characters) triggers this. You can also try to type them directly with `xdotool` to see if that reproduces the problem.

**Comment by RilicTheFox** [comment]
So I did something curious. I installed KDE Plasma and let it manage settings for the keyboards. It seems to have fixed it, even switching back to my bspwm setup and removing the `plasma`  package group.
I think it might've been a problem on my end, maybe a missing package or something that I didn't know I needed. Should this issue be closed?

**Comment by fdw** [comment]
If you don't experience the problem anymore, we can close it, I'd say. Feel free to re-open if you see it again, though 🙂
