### ISSUE TITLE
dependencies not found

### ISSUE THREAD

**Issue by farzin-az** [fdw/rofi-rbw#37]
I installed your package using pip and when I run rofi-rbw in terminal I get the following:

Could not find a valid way to type characters. Please check the required dependencies.

I have a minimal install of nixos so I think I have some lacking dependencies, but I'm not sure what they are.

**Comment by fdw** [comment]
You're right, that's missing in the Readme. I'll add that later.

Depending on whether you're on X11 or Wayland, you need either `xdotool` or `wtype`. If you want to also copy stuff to the clipboard, you need one of `xsel`, `xclip` or `wl-copy`.
