### ISSUE TITLE
Way to clear clipboard after copy

### ISSUE THREAD

**Issue by das-s** [fdw/rofi-rbw#39]
Hi, is there currently a way to clear clipboard content after a certain time? Looking around I haven&rsquo;t found a proper option, neither in `xclip/xsel` nor in `rofi-rbw` itself.

**Comment by fdw** [comment]
You're right, this isn't supported yet. But I think it's a good idea, so I'll try to figure out an implementation when I have time 🙂

If you want to have a go, feel free!

**Comment by das-s** [comment]
Cool, I'll try myself at a solution :)

**Comment by fdw** [comment]
Thanks again!
