### ISSUE TITLE
[Bug] Additional args are not being passed to the action menu

### ISSUE THREAD

**Issue by das-s** [fdw/rofi-rbw#43]
I might have stumbled upon another problem: I set my specific rofi theme via the `--selector-args '-theme /home/das-s/.config/rofi/appmenu.rasi'` . Then, using the new action menu it appears to reset the theme when entering the selector menu. A possible cause might be [here](https://github.com/fdw/rofi-rbw/blob/main/src/rofi_rbw/rofi_rbw.py#L229).
Is there a reason to pass an empty list to the `additional_args` parameter or is this just an oversight?

**Comment by fdw** [comment]
Thanks for finding this! It was not done on purpose, but now I wonder if there are any arguments that work for the main menu but not for the autotype menu... I guess we'll see 😉
