### ISSUE TITLE
[Bug] `ydotool` breaking changes

### ISSUE THREAD

**Issue by gegnew** [fdw/rofi-rbw#46]
I think that [changes to ydotool](https://github.com/ReimuNotMoe/ydotool/blame/master/README.md#L17) break `rofi-rbw`, with the error:

```
ydotool: Unknown command: sleep
Run 'ydotool help' if you want a command list
```

Edit:

Actually, that error doesn't appear any more after I update my `sudoers` file with:

```
your_username ALL=(ALL) NOPASSWD: /usr/bin/ydotool
```

The `bitwarden-rofi` docs have:
> Wayland Users: For autotyping to work in Wayland, you will need [ydotool](https://github.com/ReimuNotMoe/ydotool) working with root permissions (it needs access to /dev/uinput) without asking for password. For example, this can be achieved by adding this line in visudo:

However, some other things I've noticed:
- invoking `rofi-rbw` with `sway` doesn't work at all (nothing happens)
- it would be great to have configurable keybindings, since for many i3 and sway users, Alt is already bound as their modifier key

**Comment by fdw** [comment]
Regarding the error: I think #44 already fixes this. Can you confirm this?

> Actually, that error doesn't appear any more after I update my sudoers file

I don't think that has anything to do with it. However, I don't use Wayland or `ydotool`, so I can't test it. If you have any suggestions how to set it up, please help me improve the documentation 🙂

> invoking rofi-rbw with sway doesn't work at all (nothing happens)

Have you started it from the console? Does it output some error?

> it would be great to have configurable keybindings, since for many i3 and sway users, Alt is already bound as their modifier key

Can you please open a new ticket for that? Then I can see what to do about that - or do you want to try to implement it?
