### ISSUE TITLE
Not working with wofi

### ISSUE THREAD

**Issue by TinfoilSubmarine** [fdw/rofi-rbw#51]
I have rofi-rbw 1.0.0 installed from Void and when I try to use it with wofi, it does not type (wtype), print to stdout, or copy (wl-copy). However, when I use rofi, it does work.

I've already confirmed that removing all of my user configuration for wofi does not chance anything.

**Comment by fdw** [comment]
I think I found the problem... could you please try the branch `fix/51`?
Thank you! 🙂

**Comment by TinfoilSubmarine** [comment]
Yes, that fixes it :)

**Comment by TinfoilSubmarine** [comment]
Oh, and thanks so much!

**Comment by fdw** [comment]
You're welcome 🙂
