### ISSUE TITLE
unable to copy TOTP when pressing Alt+T

### ISSUE THREAD

**Issue by eyadsibai** [fdw/rofi-rbw#55]
When I type Alt+T I just type t instead of copying the TOTP

**Comment by fdw** [comment]
Can you describe a bit more about your setup, please? Are you using `wofi` or `rofi`? Have you defined any settings or parameters?

**Comment by eyadsibai** [comment]
rofi ... no settings or parameters

**Comment by eyadsibai** [comment]
running on nixos latest version

**Comment by fdw** [comment]
Okay, that was a stupid typo... should be fixed now on `main`. Can you please test it?

**Comment by eyadsibai** [comment]
Thanks! it works now!

**Comment by eyadsibai** [comment]
Looking forward for the release 😃
