### ISSUE TITLE
Keyboard broken after use

### ISSUE THREAD

**Issue by nB82DXcx8L2jrXyw** [fdw/rofi-rbw#56]
I found this project today and was really happy about it, but there is one bug that annoys me a lot and that is something that I think has been mentioned [here](https://github.com/fdw/rofi-rbw/issues/19) and [here](https://github.com/fdw/rofi-rbw/issues/15).

When I've used the autotype feature my alt-key is messed up. It's like my alt-key is pressed down. To solve this I have to press alt one time and then everything becomes normal again.

The other issue said it might be some kind of weird character that is messing things up, but that is not the case for me. I have to autotype the password (it's not breaking if i just autotype username) for it to break, and it is breaking without any weird characters. It breaks with only numbers and/or the alphabet as well.

I don't know if this issue is a bug of rofi-rbw or xdotool, but since the other issues was kind of old and closed without a fix, I figured i should create another one.

**Comment by fdw** [comment]
From your description, it sound like you're hit with https://github.com/jordansissel/xdotool/issues/43 , and unfortunately, there's nothing I can do about that (it annoys me, too, sometimes).

However, you also linked #15, which is about the window not receiving any keystrokes. Is that true for you as well?

**Comment by nB82DXcx8L2jrXyw** [comment]
@fdw Thanks for the answer. I guess I misunderstood #15 then. It's not a major issue and I guess I'll just have to accept it if that issue been open 8 years.

**Comment by fdw** [comment]
Sorry, really :(

I'd love to fix this, but I don't think I can do this in `rofi-rbw` alone :/

**Comment by symphorien** [comment]
would it be possible to run `xdotool keyup Shift_L Shift_R Alt_L Alt_R` after xdotool as suggested in the issue in the xdottool repo? (Shift is required for layouts where numbers are accessed with shift like azerty)

**Comment by fdw** [comment]
First, I've pushed at a branch at `release-alt` to test this out. Can you please report back if this is better?

Secondly, I'd really love the implementation from @scgtrp and would prefer that if it becomes available.

**Comment by symphorien** [comment]
oh my understanding was that it must be run before, so I was trying https://github.com/symphorien/rofi-rbw/commit/f0dae81da9563f22c970364c64a78f006cda3aad (which has be working for 3 days, fwiw)

**Comment by fdw** [comment]
I think both ways should work (theoretically 😉), though slightly differently: Doing it first means that we don't have to do `--clearmodifiers`, which in turn means that the keys can't get stuck.

Doing it after still requires `--clearmodifiers`, but releases them afterwards, in case they got stuck.

If you've tested your way and it works, why don't you open a PR for it? I don't like to take credit for your idea and work 🙂

**Comment by symphorien** [comment]
I'll test a few more days, and then open a PR

**Comment by fdw** [comment]
Awesome, thank you 🙂
