### ISSUE TITLE
Invalid sleep time for `wtype`

### ISSUE THREAD

**Issue by tosti007** [fdw/rofi-rbw#57]
In PR #52, a default type delay of `0ms` is added for all typers. As mentioned in that PR `wtype` already uses a default delay of `0ms`.
However I just noticed that using `-d 0` with wtype results in an error, i.e.:

```
% wtype -d 0 'Hello World'
Invalid sleep time
```

Meaning that using `wtype` does not allow you to type in the current state. I think the easiest solution is to remove the delay 0 argument, as it's also the default. Alternativly, adding typer arguments as discussed in PR #52 would also solve this issue, what do you think?

**Comment by fdw** [comment]
I'd prefer not to add more arguments until really necessary. Ideally, `rofi-rbw` should be easy to use, so no necessary configuration and "just works". Every parameter moves us further away from that 😉

So I just fixed the delay. Can you please check if it works now?

**Comment by tosti007** [comment]
That's alright! I didn't have time to check it yet, but this would also have been the change I'd made (and the only one I can think of) so I'll close this.
