### ISSUE TITLE
TOTP not working if two items have same name

### ISSUE THREAD

**Issue by Lem** [fdw/rofi-rbw#59]
I've come across a situation were grabbing the TOTP is not working. In said situation there are two items with the same name but different usernames.

![rofi-rbw](https://user-images.githubusercontent.com/199086/193468499-72bb8684-8d42-4ed8-a05f-1ed569a32fcd.png)
 
The result with this setup is an empty string in the clipboard. So checking how rofi-rbw is grabbing the TOTP I get this on the commandline:

```console
[lem@host rofi_rbw]$ rbw code sandwich --folder server/hetzner
rbw code: couldn't find entry for 'sandwich': multiple entries found: root@sandwich, luks@sandwich
```
Would it be possible to add the functionality that rofi-rbw adds the username to the TOTP-command if there are multiple items?

**Comment by fdw** [comment]
Interesting edge case you have there 😉

Just quickly, before I look deeper into the code: Which version of `rofi-rbw` are you running?
And is it only broken for TOTP?

**Comment by Lem** [comment]
I'm using these versions:

rofi-rbw 1.0.1
rbw 1.4.3
Vaultwarden 1.25.2

**Comment by fdw** [comment]
It's not the prettiest solution, but it should be working now. Can you please test it?

**Comment by Lem** [comment]
Can confirm that it works now :+1:
