### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by mochaaP** [fdw/rofi-rbw#61]
The current keybinding conflicts with my WM config.
It would be nice if you add an option to change the keybindings.

Thanks ;)

**Comment by fdw** [comment]
I am so sorry that I never even replied to you! 🙈

I've seen your request and actually thought a bit about it, but then other things came up and I didn't realize I never even left a comment. Sorry!

Regarding your request: Code-wise, this adds some boilerplate, but it is useful in some cases. Did you have any special key bindings in mind?

**Comment by mochaaP** [comment]
> I am so sorry that I never even replied to you! :see_no_evil: 

Nevermind! It's okay.

In my case `Alt+t` does not work.

**Comment by fdw** [comment]
This was quite involved, but I think I've found a nice way to do it. Can you please check it out on the branch `custom-shortcuts` and see if it works for you?

For the protocol, this also makes #49 redundant.

**Comment by fdw** [comment]
Did you have a chance to test it yet? I wouldn't want to merge it without someone else trying it out.

**Comment by mochaaP** [comment]
> Did you have a chance to test it yet?

Not yet. Currently working on my new setup but I will test it as soon as I finished it :)

**Comment by fdw** [comment]
I'd like to merge this and release a new version. Could you test it yet?

**Comment by mochaaP** [comment]
Yeah, right now.

**Comment by mochaaP** [comment]
Worked flawlessly. Thank you!

**Comment by mochaaP** [comment]
One small issue, throws an exception on quit:
```python
Traceback (most recent call last):
  File "/home/mochaa/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mochaa/.local/pipx/venvs/rofi-rbw/lib64/python3.11/site-packages/rofi_rbw/__main__.py", line 5, in main
    RofiRbw().main()
  File "/home/mochaa/.local/pipx/venvs/rofi-rbw/lib64/python3.11/site-packages/rofi_rbw/rofi_rbw.py", line 182, in main
    targets, action = self.__show_target_menu(
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by fdw** [comment]
Thank you 🙂
I think I've fixed the problem (assuming you used `Esc` to quit `rofi-rbw`) and merged everything to master.

I'll close the ticket, but if there's something left, feel free to re-open 🙂
