### ISSUE TITLE
Is there any way to unlock rofi-rbw without having to enter the password?

### ISSUE THREAD

**Issue by andradeexperiments** [fdw/rofi-rbw#62]
Every time I restart the system I need to enter the master password, which is a lot since it has 30 digits.

**Comment by fdw** [comment]
`rofi-rbw` is only a front-end to [`rbw`](https://github.com/doy/rbw). As far as I know, that doesn't have a feature to automatically unlock the vault. (I'm also not sure if that is a good idea, to be honest.)

But why is it prompting after each restart? Are you automatically starting `rofi-rbw`?

**Comment by andradeexperiments** [comment]
> But why is it prompting after each restart? Are you automatically starting `rofi-rbw`?

No, I say that when I restart my pc, I have to run "rofi-rbw" in the terminal and write my password

**Comment by fdw** [comment]
I see, thanks 🙂

I would expect unlocking without a password would be quite a security risk, so it's not implemented in `rbw`. Feel free to open a feature request there, though. But it's not something `rofi-rbw` can do, sorry, as the whole unlocking process is managed by `rbw`.
