### ISSUE TITLE
Unable to launch rofi-rbw from i3.

### ISSUE THREAD

**Issue by SeraphimRP** [fdw/rofi-rbw#69]
Hello!

Thank you for the awesome tool! I've been having a particular issue launching it from i3, and I'm curious if there's anything on the internals of rofi-rbw that could be causing this.

It's probably unlikely that the initial run of rofi-rbw (which sends to unlock rbw) would work through a keybind, but I'm not sure why it wouldn't work to just `exec rofi-rbw` from an i3 keybind.

Just hoping to get your insight.

Thanks!

**Comment by fdw** [comment]
Hey, thanks for the compliments 😊

Could you please describe the error you're seeing?
I use `rofi-rbw` exactly as you suggested, starting it all the time from [`exec rofi-rbw`](https://github.com/fdw/dotfiles/blob/main/i3/config#L13), and that works fine including the initial unlocking.

**Comment by SeraphimRP** [comment]
Very strange.

Attempting to start `rofi-rbw` through an i3 keybind doesn't seem to do anything. It works for other programs, so it isn't the bind. I'm not sure.

The keybind is like so:
`bindsym $mod+Shift+d exec "rofi-rbw"`

My i3 logs don't mention anything of note:
```
02/11/2023 14:01:45 - ../src/commands_parser.c:parse_command:241 - COMMAND: *exec "rofi-rbw"*
02/11/2023 14:01:45 - ../src/commands.c:cmd_criteria_init:148 - Initializing criteria, current_match = 0x2765d8
02/11/2023 14:01:45 - ../src/commands.c:cmd_exec:1298 - should execute rofi-rbw, no_startup_id = 0
02/11/2023 14:01:45 - startup id = i3/rofi-rbw/9358-5-bsd_TIME6530559
02/11/2023 14:01:45 - executing: rofi-rbw
02/11/2023 14:01:45 - ../src/commands.c:cmd_criteria_init:148 - Initializing criteria, current_match = 0x2765d8
02/11/2023 14:01:45 - ../src/ipc.c:ipc_send_binding_event:1682 - Issue IPC binding run event (sym = d, code = 0)
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 33, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 33, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 33, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 33, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 33, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 17, xkb_base 85
02/11/2023 14:01:45 - ../src/handlers.c:handle_destroy_notify_event:540 - destroy notify for 0x00600040, 0x00600040
02/11/2023 14:01:45 - ../src/handlers.c:handle_unmap_notify_event:469 - UnmapNotify for 0x00600040 (received from 0x00600040), serial 1108
02/11/2023 14:01:45 - Not a managed window, ignoring UnmapNotify event
02/11/2023 14:01:45 - ../src/handlers.c:handle_event:1384 - event type 3, xkb_base 85
02/11/2023 14:01:45 - ../src/key_press.c:handle_key_press:23 - KeyRelease 50, state raw = 0x41
02/11/2023 14:01:45 - ../src/bindings.c:get_binding_from_xcb_event:318 - (removed capslock, state = 0x41)
02/11/2023 14:01:45 - ../src/bindings.c:get_binding_from_xcb_event:343 - (transformed keyboard group, state = 0x10041)
```

I'm not sure where else I could find relevant logs about this.

**Comment by fdw** [comment]
How did you install `rofi-rbw`? And can you launch it from the command line? Or with a different keybinding?

**Comment by SeraphimRP** [comment]
1. `pip`
2. Yep, no issues there.
3. Not with a different keybind.

It's very well possible this is an i3 issue, I made this issue just in case there was anything on this end that could be causing it.

**Comment by fdw** [comment]
Did you install it globally or just for your user? And did you define the absolute path in the i3 configuration?
I can imagine that for some reason, i3 can't find the binary.

**Comment by SeraphimRP** [comment]
Yeah, so, took this to i3's IRC. It ended up being a path issue. Ended up c+p'ing `rbw` and the `rofi-rbw` launch script into `/usr/local/bin`.

The only thing now is getting it to prompt me for the master password, but I suppose that's beyond the scope of this issue?

Thanks for the help!

**Comment by fdw** [comment]
That should also "just work". If you use `rbw` on the command line, does that work?

**Comment by SeraphimRP** [comment]
Yes, `rbw` on CLI just works. However, a terminal doesn't spawn for me if `rbw` needs a password when I use the keybind.

**Comment by SeraphimRP** [comment]
It's worth noting here that I was on FreeBSD. However, on Arch it works just as intended - in part because `rbw` is packaged. I'm not sure what the issue is regarding the initial password prompt, but it might be related to having `pinentry` installed.

Considering I'm not on FreeBSD at this point, I suppose there's nothing more I can ask for. Thanks again for the assistance!

**Comment by fdw** [comment]
Yes, you need a compatible `pinentry` for `rbw`. I'm using the gtk3 variant, which opens a dialog window. I don't know if it opens a terminal window by itself if needed.

If you have any more problems, feel free to open an issue 🙂
