### ISSUE TITLE
switch to yaml config file

### ISSUE THREAD

**Issue by benedikt-bartscher** [fdw/rofi-rbw#71]
A yaml config would be more convenient. It's pretty easy to implement with https://github.com/omni-us/jsonargparse/

**Comment by fdw** [comment]
Could you please illustrate in more detail what problems you have with the current approach?

In general, I'm not too much of a fan of yaml, because of its weird quirks. And the library you suggested seems to do a lot more than what I want. Maybe we can find another solution?

**Comment by fdw** [comment]
As I don't see the advantage of migrating to yaml, I'll close this for now. If you have a new reason, feel free to re-open.
