### ISSUE TITLE
Filter's out number `3` from password if using `Alt+3` to type password directly

### ISSUE THREAD

**Issue by georgesboris** [fdw/rofi-rbw#73]
**Steps to reproduce**

```bash
rbw add Test # write 123456 as password
rofi-rbw --no-help
```

Select "Test" entry and press `Alt+3`. The password is printed as `12456`.

If the password is printed using `Return` through `rofi-rbw --no-help -t password` then everything works!

**System**

```
NixOS (unstable)
rofi-rbw 1.1.0
DE xmonad
Typer xdotool
```

---

This was sooo tricky to notice haha -- I hope this report helps in finding the fix!

**Comment by fdw** [comment]
I fear this is a problem with `xdotool`. If you keep `Alt+3` pressed for longer, does it work then?

**Comment by benedikt-bartscher** [comment]
i can only reproduce this if i hold Alt+3 for a long time

**Comment by fdw** [comment]
Thanks for testing it! With normal usage it works as desired?

**Comment by benedikt-bartscher** [comment]
Yes, i never experienced this issue with normal usage. I just tested it out of curiosity

**Comment by georgesboris** [comment]
Hey folks, I also think this a problem with `xdotool` but I haven't been able to find where... I've only been using it with `-t password` to bypass the issue so I'm not feeling the pain anymore.

maybe it would be worth to have just a small heads-up for `xdotool` users. I'm fine with closing! :)

**Comment by fdw** [comment]
Okay, I'll close. If anyone has the same bug, feel free to re-open! 🙂
