### ISSUE TITLE
New release with dotool support

### ISSUE THREAD

**Issue by TinfoilSubmarine** [fdw/rofi-rbw#75]
Hi, was just wondering if @fdw or anyone else has had a chance to test dotool support out? It's been in for awhile so was wondering if we could get a release.

**Comment by fdw** [comment]
Hey! I haven't tested it, but there also haven't been any complaints 😉

If you don't mind, I'd like to wait for #74 for a bit before I put out the next release.

**Comment by fdw** [comment]
Should be out now - have fun! 🙂
