### ISSUE TITLE
I still see the issue where you cannot copy/type data from a custom field named 'password', even though it is visible.

### ISSUE THREAD

**Issue by fdw** [fdw/rofi-rbw#77]
I still see the issue where you cannot copy/type data from a custom field named 'password', even though it is visible.

Steps to reproduce:

- Create login entry, leave password empty
- add custom field with name `password`
- try to copy the custom data

Result: empty clipboard
Expected: custom data in clipcoard

_Originally posted by @mindrunner in https://github.com/fdw/rofi-rbw/issues/74#issuecomment-1600362518_

**Comment by fdw** [comment]
I think my biggest question is: Why would you do that? 😉

The best way to solve this would mean that custom fields are distinguishable from built-in fields when showing them in `rofi`, so instead of `Password: 1*****`, it would show `Field Password: 1*****`, for all fields. I'm not sure I find that an acceptable trade-of for - what I guess - is a very unusual issue.

But if you can convince me that this happens often (or that there is a better way), I'm open 🙂

**Comment by mindrunner** [comment]
> I think my biggest question is: Why would you do that?

Well, bitwarden supports ist. So having undefined or non-expected behaviour on this, would always confuse/annoy users. I do store a lot non-web related things and use those fields for it because i usually need more than just username/password combinations.

![image](https://github.com/fdw/rofi-rbw/assets/1413542/aa8de561-d227-4a68-8051-540cd446622d)

In this specific case, I stored the same value into both (as a workaround for this issue). since I know whats going on, I can also easily identify which one is which. We could also place a divider line before the custom fields here to make it even more clear.


Imo, the problem is not visibility here, but rather the inability to copy/type the custom field with that name. As soon as a custom field is named 'password', it cannot be accessed with rofi-rbw.

**Comment by fdw** [comment]
Sorry for taking a bit with this issue.

The main problem is that `rofi-rbw` depends on the "name" to know which field to use. For example, "Password" is mapped to the password field, and anything unknown is taken as a custom field.
Using that scheme, how could it distinguish between the "normal" password field and a custom field called "password"? The only solution that comes to my mind is prefixing fields, like I suggested in the my last comment. Then, it would be clear whether you want a custom field or a default field, but at the expense of adding "Field" to all of them. And I'm still not convinced that that is a good trade-off.

**Comment by mindrunner** [comment]
I think, prefixing is a valid solution in this case. I played around with the code a bit and it seems pretty straight forward. Just adding `extra/...` as a prefix fixed that issue for me.

**Comment by fdw** [comment]
As you may have noticed, I wasn't convinced by the previous ideas. However, if we can just rename the fields that conflict with the "common" ones, we can still solve your (uncommon 😉) problem while not impacting anyone else.

I've tried to implement just that on the branch `feature/fields-with-reserved-names`. Can you please test it and report back?

**Comment by fdw** [comment]
Hey @mindrunner, have you had a chance yet to try out the branch?

**Comment by mindrunner** [comment]
sorry for delay
I am not sure what you did not and what I can expect it to be in terms of the behaviour.

For me it still behaves in a somewhat weird way, e.g. it crashed if the password field is empty and does not let me copy the correct field if there are multiple entries with the same name, e.g. 'password'

**Comment by fdw** [comment]
No worries, we all have lives 😉

If you use the branch `feature/fields-with-reserved-names`, a field called "password" should now be shown and treated (fe copied or typed) correctly. It definitely should not crash 😉

However, multiple fields with the same name are still unsupported, as they haven't been mentioned yet. But this looks like an edge case, too, as I cannot imagine how you can distinguish them in any other UI, either.

**Comment by fdw** [comment]
Hey @mindrunner, did you have a chance to test it yet?

**Comment by mindrunner** [comment]
Does not work for me here. Still behaves weirdly. `password` field is not copied at all. `Password` will be shown as `(Field)` suffix. Not sure what to do and how to proper test that to be honest.

**Comment by fdw** [comment]
Thanks! Yes, the casing was the problem - I only tried an upper-case "Password" field and that already worked as expected.

Now, it should hopefully work for "password" as well 🙂

**Comment by mindrunner** [comment]
Cool, thank you for fixing :)

**Comment by fdw** [comment]
Just to make sure: It works now?

If yes, I'll merge it.

**Comment by mindrunner** [comment]
yep, all good. thank you :)

**Comment by fdw** [comment]
Thank you, and merged 🙂
