### ISSUE TITLE
show username/url

### ISSUE THREAD

**Issue by Azulinho** [fdw/rofi-rbw#78]
Hi there,

Is there a way to show the username/url instead of the title of the bitwarden entry?

![image](https://github.com/fdw/rofi-rbw/assets/851757/9c7e7cb4-508f-4270-b438-ee9fe0358247)

similar to the output of
```
rbw list --fields name,user
```

**Comment by fdw** [comment]
Hey, I think I understand your question, but your screenshot mostly already shows the URL - is that the title you've chosen? Would it really help if it would show the URL additionally, if it's the same one for all entries?

But, more importantly: Since [v0.5.0](https://github.com/fdw/rofi-rbw/releases/tag/0.5.0), the username should already show up in your list. Are you on a current version?

**Comment by Azulinho** [comment]
That's the title it shows, I mostly added my bitwarden entries using the bitwarden chrome plugin
which defaults to add part of the url as the title (so a lot of my bitwarden entries show up as accounts.google.com) as show below, 
I usually  search for the username in the bitwarden chrome extension to get the username/password combo like this,
![image](https://github.com/fdw/rofi-rbw/assets/851757/8a7f6ec0-e1b6-498f-b127-2fcd8da8f94b)

I was keen to be able to do the same, search by username and get the list of matches for that username, but so that it would show the username and not the title. (I guess I could rename all my bitwarden titles too....)
![image](https://github.com/fdw/rofi-rbw/assets/851757/046e42e1-7c50-4314-ac04-5af617a418b7)


```
rofi-rbw --version
rofi-rbw 1.2.0
```
from what I see, it seems that you pull that info as per: https://github.com/fdw/rofi-rbw/blob/1.2.0/src/rofi_rbw/rbw.py#L12
and consume it in https://github.com/fdw/rofi-rbw/blob/2735036973eb66dfc74c4deced4b298256ee0479/src/rofi_rbw/rofi_rbw.py#L157
feeding it back to rofi in https://github.com/fdw/rofi-rbw/blob/2735036973eb66dfc74c4deced4b298256ee0479/src/rofi_rbw/selector.py#L125
and https://github.com/fdw/rofi-rbw/blob/2735036973eb66dfc74c4deced4b298256ee0479/src/rofi_rbw/selector.py#L142

I might write some tests to figure out how the data is being passed to rofi.
as from this other ticket: https://github.com/fdw/rofi-rbw/issues/59
it shows what I assume is the username in the listing.

**Comment by Azulinho** [comment]
found it,
it was the font size in rofi
setting it to a smaller font size, it shows the username

**Comment by fdw** [comment]
Is that an acceptable solution for you?
