### ISSUE TITLE
If no `--typing-key-delay` option is provided ` wtype` fails to type

### ISSUE THREAD

**Issue by SailReal** [fdw/rofi-rbw#95]
In `rofi-rbw` version 1.4.1 but I guess also in 1.4.0, when running `rofi-rbw -t password -a type --typer wtype --selector-args="--insensitive" `, selecting an option, then there is nothing typed but it logs

```
rofi-rbw
Invalid sleep time
        Invalid sleep time
```

I think the problem was added with the new `--typing-key-delay` option in
https://github.com/fdw/rofi-rbw/blob/270437ecedd3ce699df28594ad0fc11a8506b0b2/src/rofi_rbw/argument_parsing.py#L112

and is quiet the same as in https://github.com/fdw/rofi-rbw/issues/57,  `wtype -d 0 'Hello World'` is not allowed.

My current workaroud is to add `--typing-key-delay 1` to the command above.

**Comment by SailReal** [comment]
Thanks for the fix!

What is the easiest way to run? Do I need to setup `python-poetry`?

**Comment by fdw** [comment]
Yes, I think Poetry is the easiest way. You should be able to `poetry install`, `poetry run python -m rofi_rbw`.

**Comment by SailReal** [comment]
[bd3a435](https://github.com/fdw/rofi-rbw/commit/bd3a43519efb933fb0508142620b6fe04dc7469c) fixes it :+1:

**Comment by fdw** [comment]
Thank you very much! 🙂
I've merged it to main and will release it soon.
